// AUTO-GENERATED by scripts/generate-image-manifest.mjs
export const imageManifest: Record<string, string[]> = {
  "buy-this-complete-shop": [
    "/images/products/buy-this-complete-shop/buy-this-complete-shop-cover.jpg",
    "/images/products/buy-this-complete-shop/buy-this-complete-shop-mockup-1.jpg",
    "/images/products/buy-this-complete-shop/buy-this-complete-shop-mockup-2.jpg",
    "/images/products/buy-this-complete-shop/buy-this-complete-shop-mockup-3.jpg",
    "/images/products/buy-this-complete-shop/buy-this-complete-shop-mockup-4.jpg",
    "/images/products/buy-this-complete-shop/buy-this-complete-shop-mockup-5.jpg",
    "/images/products/buy-this-complete-shop/buy-this-complete-shop-mockup-6.jpg",
    "/images/products/buy-this-complete-shop/buy-this-complete-shop-mockup-7.jpg",
    "/images/products/buy-this-complete-shop/buy-this-complete-shop-mockup-8.jpg",
    "/images/products/buy-this-complete-shop/buy-this-complete-shop-mockup-9.jpg"
  ],
  "chatgpt-side-hustles-cover": [
    "/images/products/chatgpt-side-hustles-cover/chatgpt-side-hustles-cover.jpg"
  ],
  "digital-wealth-cover": [
    "/images/products/digital-wealth-cover/digital-wealth-cover.jpg"
  ],
  "make-money-as-you-sleep-cover": [
    "/images/products/make-money-as-you-sleep-cover/make-money-as-you-sleep-cover.jpg"
  ],
  "the-art-of-giving-no-fucks-cover": [
    "/images/products/the-art-of-giving-no-fucks-cover/the-art-of-giving-no-fucks-cover.jpg",
    "/images/products/the-art-of-giving-no-fucks-cover/the-art-of-giving-no-fucks-mockup-1.png",
    "/images/products/the-art-of-giving-no-fucks-cover/the-art-of-giving-no-fucks-mockup-2.jpg",
    "/images/products/the-art-of-giving-no-fucks-cover/the-art-of-giving-no-fucks-mockup-3.jpg",
    "/images/products/the-art-of-giving-no-fucks-cover/the-art-of-giving-no-fucks-mockup-4.jpg",
    "/images/products/the-art-of-giving-no-fucks-cover/the-art-of-giving-no-fucks-mockup-5.jpg",
    "/images/products/the-art-of-giving-no-fucks-cover/the-art-of-giving-no-fucks-mockup-6.jpg"
  ]
} as const;
