// AUTO-GENERATED by scripts/generate-image-manifest.mjs
export const imageManifest: Record<string, string[]> = {
  "100-christmas-digital-products": [
    "/images/products/100-christmas-digital-products/cover.jpg",
    "/images/products/100-christmas-digital-products/1.jpg",
    "/images/products/100-christmas-digital-products/2.jpg",
    "/images/products/100-christmas-digital-products/3.jpg",
    "/images/products/100-christmas-digital-products/4.jpg",
    "/images/products/100-christmas-digital-products/5.jpg",
    "/images/products/100-christmas-digital-products/6.jpg",
    "/images/products/100-christmas-digital-products/7.jpg"
  ],
  "12-chatgpt-ai-side-streams": [
    "/images/products/12-chatgpt-ai-side-streams/cover.jpg",
    "/images/products/12-chatgpt-ai-side-streams/1.jpg",
    "/images/products/12-chatgpt-ai-side-streams/2.jpg",
    "/images/products/12-chatgpt-ai-side-streams/3.jpg",
    "/images/products/12-chatgpt-ai-side-streams/4.jpg",
    "/images/products/12-chatgpt-ai-side-streams/5.jpg",
    "/images/products/12-chatgpt-ai-side-streams/6.jpg",
    "/images/products/12-chatgpt-ai-side-streams/7.jpg",
    "/images/products/12-chatgpt-ai-side-streams/8.jpg",
    "/images/products/12-chatgpt-ai-side-streams/9.jpg"
  ],
  "ai-and-chatgpt-guides": [
    "/images/products/ai-and-chatgpt-guides/cover.jpg",
    "/images/products/ai-and-chatgpt-guides/mock-01.jpg"
  ],
  "buy-this-complete-shop": [
    "/images/products/buy-this-complete-shop/cover.jpg",
    "/images/products/buy-this-complete-shop/mock-01.jpg",
    "/images/products/buy-this-complete-shop/mock-02.jpg",
    "/images/products/buy-this-complete-shop/mock-03.jpg",
    "/images/products/buy-this-complete-shop/mock-04.jpg",
    "/images/products/buy-this-complete-shop/mock-05.jpg",
    "/images/products/buy-this-complete-shop/mock-06.jpg",
    "/images/products/buy-this-complete-shop/mock-07.jpg",
    "/images/products/buy-this-complete-shop/mock-08.jpg",
    "/images/products/buy-this-complete-shop/mock-09.jpg"
  ],
  "chatgpt-side-hustles": [
    "/images/products/chatgpt-side-hustles/cover.jpg"
  ],
  "complete-shop-packages": [
    "/images/products/complete-shop-packages/cover.jpg",
    "/images/products/complete-shop-packages/buy-this-complete-shop-mockup-1.jpg",
    "/images/products/complete-shop-packages/buy-this-complete-shop-mockup-2.jpg",
    "/images/products/complete-shop-packages/buy-this-complete-shop-mockup-3.jpg",
    "/images/products/complete-shop-packages/buy-this-complete-shop-mockup-4.jpg",
    "/images/products/complete-shop-packages/buy-this-complete-shop-mockup-5.jpg",
    "/images/products/complete-shop-packages/buy-this-complete-shop-mockup-6.jpg",
    "/images/products/complete-shop-packages/buy-this-complete-shop-mockup-7.jpg",
    "/images/products/complete-shop-packages/buy-this-complete-shop-mockup-8.jpg",
    "/images/products/complete-shop-packages/buy-this-complete-shop-mockup-9.jpg",
    "/images/products/complete-shop-packages/card.jpg"
  ],
  "cryptocurrency-secrets": [
    "/images/products/cryptocurrency-secrets/cover.jpg",
    "/images/products/cryptocurrency-secrets/1.jpg",
    "/images/products/cryptocurrency-secrets/2.jpg",
    "/images/products/cryptocurrency-secrets/3.jpg",
    "/images/products/cryptocurrency-secrets/4.jpg",
    "/images/products/cryptocurrency-secrets/5.jpg",
    "/images/products/cryptocurrency-secrets/6.jpg",
    "/images/products/cryptocurrency-secrets/7.jpg",
    "/images/products/cryptocurrency-secrets/8.jpg",
    "/images/products/cryptocurrency-secrets/9.jpg",
    "/images/products/cryptocurrency-secrets/10.jpg",
    "/images/products/cryptocurrency-secrets/11.jpg",
    "/images/products/cryptocurrency-secrets/12.jpg",
    "/images/products/cryptocurrency-secrets/13.jpg"
  ],
  "cybersecurity-trinity": [
    "/images/products/cybersecurity-trinity/cover.jpg"
  ],
  "digital-essentials-hub": [
    "/images/products/digital-essentials-hub/cover.jpg"
  ],
  "digital-wealth-ultimate-guide": [
    "/images/products/digital-wealth-ultimate-guide/cover.jpg",
    "/images/products/digital-wealth-ultimate-guide/1.jpg",
    "/images/products/digital-wealth-ultimate-guide/2.jpg",
    "/images/products/digital-wealth-ultimate-guide/3.jpg",
    "/images/products/digital-wealth-ultimate-guide/4.jpg",
    "/images/products/digital-wealth-ultimate-guide/5.jpg",
    "/images/products/digital-wealth-ultimate-guide/6.jpg"
  ],
  "easy-way-to-build-30000-a-year-passive-income": [
    "/images/products/easy-way-to-build-30000-a-year-passive-income/cover.jpg",
    "/images/products/easy-way-to-build-30000-a-year-passive-income/1.jpg",
    "/images/products/easy-way-to-build-30000-a-year-passive-income/2.jpg",
    "/images/products/easy-way-to-build-30000-a-year-passive-income/3.jpg",
    "/images/products/easy-way-to-build-30000-a-year-passive-income/4.jpg",
    "/images/products/easy-way-to-build-30000-a-year-passive-income/5.jpg",
    "/images/products/easy-way-to-build-30000-a-year-passive-income/6.jpg",
    "/images/products/easy-way-to-build-30000-a-year-passive-income/7.jpg",
    "/images/products/easy-way-to-build-30000-a-year-passive-income/8.jpg",
    "/images/products/easy-way-to-build-30000-a-year-passive-income/9.jpg",
    "/images/products/easy-way-to-build-30000-a-year-passive-income/10.jpg"
  ],
  "eating-healthy-ebook": [
    "/images/products/eating-healthy-ebook/cover.jpg",
    "/images/products/eating-healthy-ebook/1.jpg",
    "/images/products/eating-healthy-ebook/2.jpg",
    "/images/products/eating-healthy-ebook/3.jpg",
    "/images/products/eating-healthy-ebook/4.jpg",
    "/images/products/eating-healthy-ebook/5.jpg",
    "/images/products/eating-healthy-ebook/6.jpg",
    "/images/products/eating-healthy-ebook/7.jpg",
    "/images/products/eating-healthy-ebook/8.jpg",
    "/images/products/eating-healthy-ebook/9.jpg"
  ],
  "faceless-digital-marketing-plr-bundle": [
    "/images/products/faceless-digital-marketing-plr-bundle/cover.jpg",
    "/images/products/faceless-digital-marketing-plr-bundle/1.jpg",
    "/images/products/faceless-digital-marketing-plr-bundle/2.jpg",
    "/images/products/faceless-digital-marketing-plr-bundle/3.jpg",
    "/images/products/faceless-digital-marketing-plr-bundle/4.jpg",
    "/images/products/faceless-digital-marketing-plr-bundle/5.jpg",
    "/images/products/faceless-digital-marketing-plr-bundle/6.jpg",
    "/images/products/faceless-digital-marketing-plr-bundle/7.jpg",
    "/images/products/faceless-digital-marketing-plr-bundle/8.jpg",
    "/images/products/faceless-digital-marketing-plr-bundle/9.jpg"
  ],
  "fonts-and-icons": [
    "/images/products/fonts-and-icons/cover.jpg",
    "/images/products/fonts-and-icons/mock-01.jpg",
    "/images/products/fonts-and-icons/mock-02.jpg",
    "/images/products/fonts-and-icons/mock-03.jpg",
    "/images/products/fonts-and-icons/mock-04.jpg",
    "/images/products/fonts-and-icons/mock-05.jpg"
  ],
  "health-and-fitness-ebooks": [
    "/images/products/health-and-fitness-ebooks/cover.jpg",
    "/images/products/health-and-fitness-ebooks/mock-01.jpg"
  ],
  "keto-and-diet-guides": [
    "/images/products/keto-and-diet-guides/cover.jpg"
  ],
  "make-money-as-you-sleep": [
    "/images/products/make-money-as-you-sleep/cover.jpg"
  ],
  "passive-income-and-side-hustles": [
    "/images/products/passive-income-and-side-hustles/cover.jpg",
    "/images/products/passive-income-and-side-hustles/mock-01.jpg",
    "/images/products/passive-income-and-side-hustles/mock-02.jpg",
    "/images/products/passive-income-and-side-hustles/mock-03.jpg",
    "/images/products/passive-income-and-side-hustles/mock-04.jpg",
    "/images/products/passive-income-and-side-hustles/mock-05.jpg",
    "/images/products/passive-income-and-side-hustles/mock-06.jpg",
    "/images/products/passive-income-and-side-hustles/mock-07.jpg"
  ],
  "planners-and-productivity": [
    "/images/products/planners-and-productivity/cover.jpg",
    "/images/products/planners-and-productivity/mock-01.jpg",
    "/images/products/planners-and-productivity/mock-02.jpg",
    "/images/products/planners-and-productivity/mock-03.jpg",
    "/images/products/planners-and-productivity/mock-04.jpg",
    "/images/products/planners-and-productivity/mock-05.jpg"
  ],
  "plr-and-mrr-bundles": [
    "/images/products/plr-and-mrr-bundles/cover.jpg",
    "/images/products/plr-and-mrr-bundles/mock-01.jpg",
    "/images/products/plr-and-mrr-bundles/mock-02.jpg",
    "/images/products/plr-and-mrr-bundles/mock-03.jpg",
    "/images/products/plr-and-mrr-bundles/mock-04.jpg",
    "/images/products/plr-and-mrr-bundles/mock-05.jpg",
    "/images/products/plr-and-mrr-bundles/mock-06.jpg",
    "/images/products/plr-and-mrr-bundles/mock-07.jpg",
    "/images/products/plr-and-mrr-bundles/mock-08.jpg",
    "/images/products/plr-and-mrr-bundles/mock-09.jpg"
  ],
  "plr-keto-diet-secrets": [
    "/images/products/plr-keto-diet-secrets/cover.jpg",
    "/images/products/plr-keto-diet-secrets/1.jpg",
    "/images/products/plr-keto-diet-secrets/2.jpg",
    "/images/products/plr-keto-diet-secrets/3.jpg"
  ],
  "religious-ebooks": [
    "/images/products/religious-ebooks/cover.jpg",
    "/images/products/religious-ebooks/mock-01.jpg",
    "/images/products/religious-ebooks/mock-02.jpg"
  ],
  "self-help-and-how-to": [
    "/images/products/self-help-and-how-to/cover.jpg",
    "/images/products/self-help-and-how-to/mock-01.jpg",
    "/images/products/self-help-and-how-to/mock-02.jpg",
    "/images/products/self-help-and-how-to/mock-03.jpg",
    "/images/products/self-help-and-how-to/mock-04.jpg",
    "/images/products/self-help-and-how-to/mock-05.jpg",
    "/images/products/self-help-and-how-to/mock-06.jpg"
  ],
  "social-media-kits": [
    "/images/products/social-media-kits/cover.jpg",
    "/images/products/social-media-kits/mock-01.jpg",
    "/images/products/social-media-kits/mock-02.jpg",
    "/images/products/social-media-kits/mock-03.jpg",
    "/images/products/social-media-kits/mock-04.jpg",
    "/images/products/social-media-kits/mock-05.jpg",
    "/images/products/social-media-kits/mock-06.jpg"
  ],
  "the-art-of-giving-no-fucks": [
    "/images/products/the-art-of-giving-no-fucks/cover.jpg",
    "/images/products/the-art-of-giving-no-fucks/the-art-of-giving-no-fucks-mockup-1.jpg",
    "/images/products/the-art-of-giving-no-fucks/the-art-of-giving-no-fucks-mockup-2.jpg",
    "/images/products/the-art-of-giving-no-fucks/the-art-of-giving-no-fucks-mockup-3.jpg",
    "/images/products/the-art-of-giving-no-fucks/the-art-of-giving-no-fucks-mockup-4.jpg",
    "/images/products/the-art-of-giving-no-fucks/the-art-of-giving-no-fucks-mockup-5.jpg",
    "/images/products/the-art-of-giving-no-fucks/the-art-of-giving-no-fucks-mockup-6.jpg"
  ],
  "video-courses-and-training": [
    "/images/products/video-courses-and-training/cover.jpg"
  ],
  "web-templates": [
    "/images/products/web-templates/cover.jpg",
    "/images/products/web-templates/thumb-02.jpg",
    "/images/products/web-templates/thumb-03.jpg",
    "/images/products/web-templates/thumb-04.jpg",
    "/images/products/web-templates/thumb-05.jpg",
    "/images/products/web-templates/thumb-06.jpg",
    "/images/products/web-templates/thumb-07.jpg",
    "/images/products/web-templates/thumb-08.jpg",
    "/images/products/web-templates/thumb-09.jpg",
    "/images/products/web-templates/thumb-10.jpg",
    "/images/products/web-templates/thumb-11.jpg",
    "/images/products/web-templates/thumb-12.jpg",
    "/images/products/web-templates/thumb-13.jpg",
    "/images/products/web-templates/thumb-14.jpg",
    "/images/products/web-templates/thumb-15.jpg"
  ]
} as const;
